In [1]:
import numpy as np

In [2]:
a = np.array([2,3,4]) #creating array by several ways
a                      # method 1

array([2, 3, 4])

In [3]:
b = np.array([(1.4,2.3),(4,6,8)])  # method 2
b  # array transform sequences of sequences into 2d,3d array

array([(1.4, 2.3), (4, 6, 8)], dtype=object)

In [7]:
c = np.array( [ [2,2], [3,4] ], dtype=complex ) #3
c

array([[2.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [11]:
#(creating array by using zero,one,empty)

In [12]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
np.ones((3, 4, 5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [14]:
np.empty((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
np.arange( 15, 30, 5 ) # using aarange function

array([15, 20, 25])

In [17]:
np.arange( 10, 30, 5.5 ) # using floating points

array([10. , 15.5, 21. , 26.5])

In [18]:
a = np.arange(8)  #printing arrays

In [19]:
print (a)                           #1d array

[0 1 2 3 4 5 6 7]


In [22]:
b = np.arange(24).reshape(2,3,4)

In [24]:
print (b)        #3d array

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [25]:
                 #Universal functions (sin, cos,exp)

In [26]:
a = np.arange (4)
a

array([0, 1, 2, 3])

In [27]:
np.exp(a)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692])

In [28]:
np.sin(a)

array([0.        , 0.84147098, 0.90929743, 0.14112001])

In [29]:
np.cos(a)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 ])

In [31]:
a = np.arange(10)**3 # indexing 1d array
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [32]:
a[2] #indexing

8

In [33]:
a[2:5] # slicing

array([ 8, 27, 64], dtype=int32)

In [36]:
a[:2:5] = 1000;
a

array([1000,    1,    8,   27,   64,  125,  216,  343,  512,  729],
      dtype=int32)

In [40]:
a = np.arange(15).reshape(3, 5) # basic functions
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [41]:
a.shape            #1

(3, 5)

In [42]:
a.ndim              #2

2

In [43]:
a.dtype.name        #3

'int32'

In [44]:
a.itemsize         #4

4

In [45]:
a.size          #5

15

In [46]:
type(a)         #6

numpy.ndarray

In [47]:
#Create a 1D array of numbers from 0 to 9
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
 #create a boolean array (3x3 of all true)
np.full((3,3), True, dtype = bool)  

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [50]:
#Extract all odd numbers from arr
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
a[a % 2 == 1]

array([1, 3, 5, 7, 9])

In [51]:
#Convert a 1D array to a 2D array with 2 rows
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
arr = np.arange(10)
arr.reshape(2, -1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [53]:
 # Stack arrays a and b vertically
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
np.vstack([a, b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [54]:
#Stack the arrays a and b horizontally.
a = np.arange(10).reshape(2,-1)

b = np.repeat(1, 10).reshape(2,-1)
np.hstack([a, b])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [55]:
#Get the common items between a and b
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)

array([2, 4])

In [56]:
#From array a remove all items present in array b
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

np.setdiff1d(a,b)

array([1, 2, 3, 4])

In [60]:

#Get all items between 5 and 10 from a.

a = np.arange(10)

index = np.where(np.logical_and(a>=5, a<=10))
a[index]

array([5, 6, 7, 8, 9])